CREATE  TABLE public.countries (
  name text NOT NULL,
  alpha-2 text NOT NULL,
  alpha-3 text NOT NULL,
  country-code bigint NOT NULL,
  iso_3166-2 text NOT NULL,
  region text NULL,
  sub-region text NULL,
  intermediate-region text NULL,
  region-code bigint NULL,
  sub-region-code bigint NULL,
  intermediate-region-code bigint NULL,
  CONSTRAINT Countries_pkey PRIMARY KEY ("alpha-3"),
  CONSTRAINT Countries_alpha-2_key UNIQUE ("alpha-2"),
  CONSTRAINT Countries_alpha-3_key UNIQUE ("alpha-3"),
  CONSTRAINT Countries_country-code_key UNIQUE ("country-code"),
  CONSTRAINT Countries_iso_3166-2_key UNIQUE ("iso_3166-2"),
  CONSTRAINT Countries_name_key UNIQUE (name)
) TABLESPACE pg_default;


create table public.leaderboard (
  id smallint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  time time without time zone not null,
  score bigint not null,
  user_id uuid null,
  constraint LeaderboardEntries_pkey primary key (id),
  constraint leaderboard_user_id_fkey foreign KEY (user_id) references profiles (id)
) TABLESPACE pg_default;


create table public.profiles (
  id uuid not null,
  username text null,
  email text null,
  country_id text null,
  role_id smallint null,
  constraint profiles_pkey primary key (id),
  constraint profiles_email_key unique (email),
  constraint profiles_username_key unique (username),
  constraint profiles_id_fkey foreign KEY (id) references auth.users (id) on delete CASCADE,
  constraint profiles_country_id_fkey foreign KEY (country_id) references countries ("alpha-3"),
  constraint profiles_role_id_fkey foreign KEY (role_id) references roles (id),
  constraint username_length check ((char_length(username) >= 3))
) TABLESPACE pg_default;


create table public.roles (
  id smallint generated by default as identity not null,
  name text not null,
  new_entry boolean not null,
  validate_entry boolean not null,
  edit_entry boolean not null,
  constraint Roles_pkey primary key (id),
  constraint Roles_id_key unique (id)
) TABLESPACE pg_default;